### ISSUE TITLE
No colored text is shown

### ISSUE THREAD

**Issue by kookma** [szaghi/FACE#4]
Hi Stefano,
 Compiling and running the FACE with gfortran 8.0.1 on Windows 10 with face_test_basic produces the following output:
`
[91mForeground colors samples[0m
  colorize("BLACK          ", color_fg="BLACK          ") => [30mBLACK          [0m code: [7m[30m30[0m[0m
  colorize("RED            ", color_fg="RED            ") => [31mRED            [0m code: [7m[31m31[0m[0m
  colorize("GREEN          ", color_fg="GREEN          ") => [32mGREEN          [0m code: [7m[32m32[0m[0m
  colorize("YELLOW         ", color_fg="YELLOW         ") => [33mYELLOW         [0m code: [7m[33m33[0m[0m
  colorize("BLUE           ", color_fg="BLUE           ") => [34mBLUE           [0m code: [7m[34m34[0m[0m
  colorize("MAGENTA        ", color_fg="MAGENTA        ") => [35mMAGENTA        [0m code: [7m[35m35[0m[0m
  colorize("CYAN           ", color_fg="CYAN           ") => [36mCYAN           [0m code: [7m[36m36[0m[0m
  colorize("WHITE          ", color_fg="WHITE          ") => [37mWHITE          [0m code: [7m[37m37[0m[0m
  colorize("DEFAULT        ", color_fg="DEFAULT        ") => [39mDEFAULT        [0m code: [7m[39m39[0m[0m
  colorize("BLACK_INTENSE  ", color_fg="BLACK_INTENSE  ") => [90mBLACK_INTENSE  [0m code: [7m[90m90[0m[0m
  colorize("RED_INTENSE    ", color_fg="RED_INTENSE    ") => [91mRED_INTENSE    [0m code: [7m[91m91[0m[0m
  colorize("GREEN_INTENSE  ", color_fg="GREEN_INTENSE  ") => [92mGREEN_INTENSE  [0m code: [7m[92m92[0m[0m
  colorize("YELLOW_INTENSE ", color_fg="YELLOW_INTENSE ") => [93mYELLOW_INTENSE [0m code: [7m[93m93[0m[0m
  colorize("BLUE_INTENSE   ", color_fg="BLUE_INTENSE   ") => [94mBLUE_INTENSE   [0m code: [7m[94m94[0m[0m
  colorize("MAGENTA_INTENSE", color_fg="MAGENTA_INTENSE") => [95mMAGENTA_INTENSE[0m code: [7m[95m95[0m[0m
  colorize("CYAN_INTENSE   ", color_fg="CYAN_INTENSE   ") => [96mCYAN_INTENSE   [0m code: [7m[96m96[0m[0m
  colorize("WHITE_INTENSE  ", color_fg="WHITE_INTENSE  ") => [97mWHITE_INTENSE  [0m code: [7m[97m97[0m[0m
`
No colorized text at all!
What is the problem? Is it because Windows 10 does not support ANSI colors in command window?

**Comment by szaghi** [comment]
Dear @kookma 

there should something "strange" with your shell. I have just re-ran the tests with both 7.2 and 8.x experimental branch and all work as expected. 

I guess that the Windows shell does not support the *echoing* of ANSI codes, in fact what you posted are that codes. FACE is developed targeting shells that support ANSI codes. Before I'll investigate further (that will be difficult for me because I have not a Windows PC), please verify that the shell your are using support ANSI codes formatting.

Anyway, thank you very much for reporting it.

![screenshot-2018-03-15-16-46-53_2560x1440](https://user-images.githubusercontent.com/1661942/37474657-2e61feca-2871-11e8-800b-6b7994ee5253.png)

**Comment by kookma** [comment]
Stefano,
 It seems Windows 10 cmd.exe (terminal) does not support ANSI codes! 
I tried FACE this time with ConEmu (https://conemu.github.io/) and it works like a charm!

I also did some googling and it seems not cmd.exe (Console) nor Windows powershell.exe support ANSI code!

**Comment by szaghi** [comment]
Good to know. So the Windows "console" does not support ansi codes.

I am closing this issue, let me know if I can help you further.

Thank you for reporting the issue.

Cheers.
